; Listing generated by Microsoft (R) Optimizing Compiler Version 19.15.26729.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\JONEL 1\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cpp"
